### ISSUE TITLE
Allow custom limits for park entrance fees, allow limiting park entrance fee by guests initial cash parameter

### ISSUE THREAD

**Issue by SpartanFrederic104** [Sadret/openrct2-price-manager#2]
Currently, the plugin allows for bounding the park entrance fee by either minimum, average, or maximum initial guest cash. What I would like is an option which allows a custom set limit up to a maximum of $200, alongside a fourth guest cash limiter option which is equal to the scenario's initial guest cash setting. This would be more helpful in scenario play as I commonly set my park entrance fee to the scenario's initial guest cash setting (i.e. $55 in Amity Airfield) in pay-per-entry scenarios.

**Comment by Sadret** [comment]
As this is certainly possible, I do not see the advantage of these additional options.
What would be the advantage of initial guest cash vs the existing three?
Why would you want to limit the park entrance fee by a fixed amount?

**Comment by Sadret** [comment]
Also, the "initial guest cash" value is an internal property that the normal player do not encounter. It is not really clear what "initial guest cash" should mean, as guests spawn with different amounts of money.
