### ISSUE TITLE
Shop/ride prices generating "good value" thoughts even when unticked

### ISSUE THREAD

**Issue by sudofox** [Sadret/openrct2-price-manager#3]
The plugin seems to sometimes work, but not consistently. For example, I'm struggling to get it to price things high enough in Sprightly Park. Rides/shop prices seem wayyy too low for the amount of cash the guests are carrying around.

**Comment by sudofox** [comment]
Also undercharging shop prices in Bumbly Bazaar

**Comment by Sadret** [comment]
Can't reproduce, it seems fine to me. Can you give me specific numbers? Also, note these things:
- The preexisting rides in Sprightly Park are extremly old, which decreases their value by a lot.
- If you charge for the park entry, guests not willing to pay as much.
- Shops will still sell some items if the prices are higher (up to 70 cents overcharge).
