### ISSUE TITLE
Feature: "Refurbish All" button

### ISSUE THREAD

**Issue by Kikithecat12345** [Sadret/openrct2-price-manager#4]
In OpenRCT2 there is a feature where if you click on a ride and renew it, the game treats it as if you just rebuilt the ride. Could you make a button that allows me to renew my whole park (or maybe just the rides older than some threshold) with 1 click?

**Comment by Sadret** [comment]
I think this is very much out of the scope of this plugin.
Although it affects pricing, it is not really on the topic of managing them.
