### ISSUE TITLE
Unknown custom action error

### ISSUE THREAD

**Issue by Lucius6** [Sadret/openrct2-price-manager#5]
I use the Open RCT2 launcher with develop updates enabled and since the c82c4ca update if enable automatic daily updates is checked or I I  get an unknow custom action error every new day. It also happens when you click on "update all prices now". Don't know if this is sth you gotta fix or sth the devs gotta look into but I wanted to let know this issue.

![image](https://user-images.githubusercontent.com/49132759/211176048-ade0a355-c04d-44a0-9524-80a01a33f39d.png)

**Comment by Sadret** [comment]
Already fixed in v1.1.2.

**Comment by Lucius6** [comment]
Ow, I didn't saw there was an update for this pulgin, my bad :)

**Comment by Sadret** [comment]
No problem, thanks for using my plugin!
