### ISSUE TITLE
Doesn't work annymore

### ISSUE THREAD

**Issue by Lucius6** [Sadret/openrct2-price-manager#6]
I'm playing on the latest dev build and prices don't get updated annymore, also not when trying to force it by clicking the 'update now' button.

**Comment by Sadret** [comment]
I'm on build v0.4.6-2-gcb51d63, which is the latest as of now, and everything works as expected.
Could you give more details?

**Comment by Lucius6** [comment]
Huh, strange, maybey I did sth wrong then as indeed it's working now.
