### ISSUE TITLE
"Invalid parameter" error message

### ISSUE THREAD

**Issue by cheweytoo** [Sadret/openrct2-price-manager#8]
Cause:
> https://github.com/OpenRCT2/OpenRCT2/pull/22227

Solution:
> Enable a price limit of 20 €/$ (or less).

(Edit by Sadret. Original description follows.)

---

I have built a new coaster with stats:

-  Excitement: 8.23
-  Intensity: 6.78
-  Nausea: 4.23

On the newest OpenRCT2 dev build (9d8d455), every time this plugin tries to set a ride price on this coaster, it fails with the following error message in the OpenRCT2 console: 
`ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/actions/RideSetPriceAction.cpp:69 (Query)]: Attempting to set an invalid price for rideIndex 24
`

Additionally, there's a popup with "invalid parameter" in the game:

![invalid_parameter](https://github.com/Sadret/openrct2-price-manager/assets/29800630/bf1bb9cb-5dc3-4393-84ac-73db694c7300)

**Comment by Sadret** [comment]
Hi, thanks for reporting! Could you attach the savegame?

**Comment by cheweytoo** [comment]
Sort-of-reduced testcase, "Ghost Town" scenario:

[bug_price_manager.park.zip](https://github.com/user-attachments/files/16117356/bug_price_manager.park.zip)

"Hyper Twister 1" is the coaster triggering this issue. It goes away if I set the Price Manager option "Limit prices to" to 20.00.

I guess there's a scenario setting limiting prices to 20.00?

**Comment by Sadret** [comment]
In the past it was ok to set the price higher than 20 GBP via plugins, it was just the vanilla UI that did not allow it. Maybe this was changed?

**Comment by Sadret** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/22227
For everyone having the same issue: Enable a price limit of 20 €/$... (or less).

I will limit this to 20 in the next release, which is not planned yet.

**Comment by cheweytoo** [comment]
Oh, good find! I was just about to do some bisecting with dev builds…

Wow, this will have serious consequences for cash flow in my bigger parks, where there are _many_ rides with more-than-20 price potential.

**Comment by cheweytoo** [comment]
Turns out the effect on park finances is not as big as I expected – at least for parks with lots of guests, where lower prices can be partially compensated by more guests going on rides:
https://github.com/OpenRCT2/OpenRCT2/pull/22227#issuecomment-2211987572
