### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by Harry-Hopkinson** [Sadret/openrct2-price-manager#9]
Hello, I am a big fan of your plugin and have been using it for a long time. However, I first noticed that on some parks I would get an annoying popup saying Invalid Parameter every time the prices updated. Is this due to a change in the API or am I doing something wrong?

<img width="318" alt="Screenshot 2024-08-18 at 22 05 26" src="https://github.com/user-attachments/assets/79e7eb34-d1b1-4773-a23f-2c8a4ae524a5">

**Comment by Harry-Hopkinson** [comment]
I found the fix in here - https://github.com/Sadret/openrct2-price-manager/issues/8. The game does not allow the prices of some rides to go over 20 so I just limited the price to 20. Thanks for the plugin.

**Comment by Sadret** [comment]
I'm happy that you like it!
